### PR TITLE
Wrapped up EKs setup in one script

### PR DESCRIPTION
**Pull request by srakshit**
*Issue #, if available:*

*Description of changes:*
Wrapped up EKs setup in one script, reducing manual step

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by rafael-gumiero — CHANGES_REQUESTED** [review]
Hello, please put the script in the /scripts directory to keep the project standard.

**Comment by srakshit** [comment]
> Hello, please put the script in the /scripts directory to keep the project standard.

- Moved eks-setup to scripts folder.
- Removed unnecessary CFN output
- There was a section of code in CFN which was within double try catch block, hence suppressing the actual error in the exception. Removed double try/catch block also.

**Review by rafael-gumiero — APPROVED** [review]
LGTM

**Review by rafael-gumiero — CHANGES_REQUESTED** [review]
Please keep the domain which is extremely useful in case of having multiple domains and also for troubleshooting

**Review by rafael-gumiero — APPROVED** [review]
LGTM

**Pull request merged**
